// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdYw8s--uR71MLtfuoFbnKYNpuhO8mfeY',
    appId: '1:1087549272159:web:cdc279fd63ae6d56c2abea',
    messagingSenderId: '1087549272159',
    projectId: 'instagram-clone-3faa3',
    authDomain: 'instagram-clone-3faa3.firebaseapp.com',
    storageBucket: 'instagram-clone-3faa3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMUjefK_Dfo58QrZ_LKImrGOkcOxgx1lI',
    appId: '1:1087549272159:android:b410ac5a479eaa10c2abea',
    messagingSenderId: '1087549272159',
    projectId: 'instagram-clone-3faa3',
    storageBucket: 'instagram-clone-3faa3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXvCRkLcB5a9GG3_HgVKXyIxUkmDFsPPo',
    appId: '1:1087549272159:ios:b9fe6bbc02fe391bc2abea',
    messagingSenderId: '1087549272159',
    projectId: 'instagram-clone-3faa3',
    storageBucket: 'instagram-clone-3faa3.appspot.com',
    iosClientId: '1087549272159-tia04v0qo78rh54urslkpk42v1foptnr.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
