// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVxXLqwHPlhniXlNPiHPwyHzLx91xOMkI',
    appId: '1:1067124272354:web:7a5fe4e871ea757bd782bb',
    messagingSenderId: '1067124272354',
    projectId: 'instagram-clone-1b0c8',
    authDomain: 'instagram-clone-1b0c8.firebaseapp.com',
    storageBucket: 'instagram-clone-1b0c8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDiVCxaRGsfxpT5IvM9ymO3OjNxuwkrsY',
    appId: '1:1067124272354:android:667d21a522f75120d782bb',
    messagingSenderId: '1067124272354',
    projectId: 'instagram-clone-1b0c8',
    storageBucket: 'instagram-clone-1b0c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzfmJ5qlNcPDOjKgiFUBg-luqGofz136g',
    appId: '1:1067124272354:ios:fadd4affa3f32190d782bb',
    messagingSenderId: '1067124272354',
    projectId: 'instagram-clone-1b0c8',
    storageBucket: 'instagram-clone-1b0c8.appspot.com',
    iosClientId:
        '1067124272354-kmi8kc0vmk0mpe2gbos414v4q37lgm18.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzfmJ5qlNcPDOjKgiFUBg-luqGofz136g',
    appId: '1:1067124272354:ios:fadd4affa3f32190d782bb',
    messagingSenderId: '1067124272354',
    projectId: 'instagram-clone-1b0c8',
    storageBucket: 'instagram-clone-1b0c8.appspot.com',
    iosClientId:
        '1067124272354-kmi8kc0vmk0mpe2gbos414v4q37lgm18.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramFlutter',
  );
}
